### ISSUE TITLE
`'python3' is not recognized as an internal or external command. 

### ISSUE THREAD

**Issue by NikhilDoWhile** [spywhere/Terminality#19]
OS: Windows 10
I am using Sublime Text-3 (3126). 
Python: 3.5.2   Using Anaconda

I have been using Terminality in Ubuntu earlier, and really like it. But now I am working in windows-10, and recently set up my Sublime Text- 3. 
As installing and maintaining  package of Python is not easy in Windows, there for I am using Anaconda.
But the problem is that Terminality is not able to detect Python.

Error on running Python 3:
`'python3' is not recognized as an internal or external command,
operable program or batch file.
`

Although Python-2 works just fine, in Terminality. Other packages work fine with Anaconda and are able to detect python but for some reason Terminality is showing error.

**Comment by spywhere** [comment]
Have you check that `python3` command is working properly on Command Prompt? If not, you might need to setup the `PATH` environment variable first. And also, Python 3 on Windows will install its executable file as `python` instead of `python3` so you can either change the name of the file to `python3` or use `python` for Python 3 and then use Python 2 command in the Terminality itself.

Feel free to ask me more if you missed anything. :)

**Comment by NikhilDoWhile** [comment]
![pyth1](https://cloud.githubusercontent.com/assets/9911561/22102164/77f0d4f4-de5c-11e6-8fe6-15896a44af9c.PNG)
![pyth2](https://cloud.githubusercontent.com/assets/9911561/22102165/78403e54-de5c-11e6-8af7-d13377c56f9c.PNG)

**Comment by spywhere** [comment]
Can you try Python 2 option in the Terminality?

**Comment by NikhilDoWhile** [comment]
I have not installed python 2 on my computer but still, I am able to use it in terminality could it be that it is actually accessing python3 rather than python2 here. Also python3 is not used in windows, I think rather it's python . And python is working in terminal, python 2 is not.

**Comment by spywhere** [comment]
Terminality use `python` executable for Python 2 and `python3` executable for Python 3 hence the options are described as you see. However, when you configure the `python` executable to be Python 3, it does not reflect what Terminality actually doing behind the scene. So that is why you can use Python 2 option to run your application just because Terminality use `python` executable to run regardless of what the option described. Hope that clear of what Terminality actually do. :)

**Comment by NikhilDoWhile** [comment]
Thanx, for the info. I think as in windows **python3** in path is python, hence when I am running **python2** in terminality it is actually running python-3.

**Comment by spywhere** [comment]
Yup, that's exactly what's happening.

**Comment by olivergene** [comment]
OS: Windows 10
I am using Sublime Text-3 (3126).
Python: 3.5.2 Using Anaconda

I have been using Terminality in Ubuntu earlier, and really like it. But now I am working in windows-10, and recently set up my Sublime Text- 3.
As installing and maintaining package of Python is not easy in Windows, there for I am using Anaconda.
But the problem is that Terminality is not able to detect Python.

Error on running Python 3:
`'python3' is not recognized as an internal or external command, operable program or batch file. `

Although Python-2 works just fine, in Terminality. Other packages work fine with Anaconda and are able to detect python but for some reason Terminality is showing error. I am facing this issue
