### ISSUE TITLE
Something is wrong with the ability to get current directory.

### ISSUE THREAD

**Issue by ghost** [spywhere/Terminality#21]
It seems to have some problem with getting the current directory. As you can see in the screenshot below, test.cpp is in "D1\D2\D3..D7" but when I call system("cd") from here I only see "D1".
I use Sublime Text 3, and Windows 7 SP1 if that somehow affects the plugin.
Thank you.
![untitled](https://cloud.githubusercontent.com/assets/24446667/26557178/8f1dcb7c-44c9-11e7-89f0-30e0829db309.png)

**Comment by spywhere** [comment]
Do you have any settings that you are currently set? If so, that would be helpful. Also, could you set the `debug` to `true` and try running the command again and see if there is any message in the console (`` Ctrl+` ``).

**Comment by ghost** [comment]
You mean the setting in Preference -> Package Settings -> Terminality -> Setting - User ? I didn't set anything in that file.
The Setting-Default seems to be read-only so I set the "debug" to true in Setting-User. But the message in the console is the same as before:

> Running "g++ D:\D1\D2\D3\D4\D5\D6\D7\test.cpp -o D:\D1\D2\D3\D4\D5\D6\D7\test && D:\D1\D2\D3\D4\D5\D6\D7\test "
Working dir is "D:\D1"

**Comment by ghost** [comment]
It seems that if I remove the folder D1 (Remove folder from project), it works again.
![untitled](https://cloud.githubusercontent.com/assets/24446667/26587234/f52bdeb0-457b-11e7-8470-cf3f64ec785f.png)

**Comment by spywhere** [comment]
Seems like the Terminality is working fine. However, the location where the command is the root directory of that file instead of parent directory, you could change the way it run by override the default command (take a look at README for more information on how to configure it).

The second case is fine because Terminality can only use a parent directory of that file to run.
